[package]
name = "ansi-to-tui"
version = "0.1.5"
edition = "2018"

[dependencies]
simdutf8 = { version = "0.1.0", optional = true }
tui = { version = "0.14.0", default-features = false }

[features]
simd = ["simdutf8"]
